version: '3'

services:
  db:
    image: postgres:14-alpine
    env_file:
      - ./.env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data

  django_movie:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./django_movie:/django_movie
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A django_movie worker -l info
    volumes:
      - ./django_movie:/django_movie
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - django_movie

volumes:
  pgdata: