# Generated by Django 4.0.4 on 2022-05-27 12:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='visible',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='created',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(default='', max_length=250, verbose_name='Movie category'),
        ),
        migrations.AddField(
            model_name='movie',
            name='cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Movie cost'),
        ),
        migrations.AddField(
            model_name='movie',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 5, 27), verbose_name='Premiere ending'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='movies.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_length',
            field=models.PositiveIntegerField(default=0, verbose_name='Movie length'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.URLField(default='', max_length=1000, verbose_name='Poster'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Movie rating'),
        ),
        migrations.AddField(
            model_name='movie',
            name='small_description',
            field=models.TextField(default='', verbose_name='Small description'),
        ),
        migrations.AddField(
            model_name='movie',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 5, 27), verbose_name='Premiere beginning'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Movie title'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(default='', max_length=250, verbose_name='User name'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, verbose_name='User name')),
                ('time', models.DateTimeField(default=datetime.date(2022, 5, 27), verbose_name='Movie date and time')),
                ('seat', models.PositiveIntegerField(default=0, verbose_name='Seat')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
