# Generated by Django 4.0.4 on 2022-05-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_comment_visible_remove_genre_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='end_date',
            field=models.DateField(default=None, verbose_name='Premiere ending'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='start_date',
            field=models.DateField(default=None, verbose_name='Premiere beginning'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.DateTimeField(default=None, verbose_name='Movie date and time'),
        ),
    ]
