# Generated by Django 4.0.4 on 2022-05-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_end_date_alter_movie_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cost',
        ),
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Movie price'),
        ),
    ]
