# Generated by Django 4.0.4 on 2022-05-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_name_ticket_user_remove_movie_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
    ]
