# Generated by Django 4.0.4 on 2022-05-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='small_description',
            field=models.CharField(default='', max_length=150, verbose_name='Small description'),
        ),
    ]
