# Generated by Django 4.0.4 on 2022-05-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_small_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='small_description',
            field=models.TextField(default='', max_length=150, verbose_name='Small description'),
        ),
    ]
