# Generated by Django 4.0.4 on 2022-05-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_small_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='movies.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='small_description',
            field=models.CharField(default='', max_length=150, verbose_name='Small description'),
        ),
    ]
