# Generated by Django 4.0.4 on 2022-05-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_genres_alter_movie_small_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='film_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.PositiveIntegerField(default=10, verbose_name='Movie price'),
        ),
    ]
