# Generated by Django 4.0.4 on 2022-05-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Premiere ending'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='film_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Movie length'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='small_description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Small description'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Premiere beginning'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Movie title'),
        ),
    ]
