# Generated by Django 4.0.4 on 2022-05-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_movie_description_alter_movie_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='User name'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Seat'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Movie date and time'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='User name'),
        ),
    ]
