# Generated by Django 4.0.4 on 2022-05-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_alter_comment_options_comment_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
