# Generated by Django 3.1.6 on 2022-05-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_alter_comment_options_rename_comment_comment_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.PositiveIntegerField(blank=True, null=True, verbose_name='Seat')),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of movie'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Seat count'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ticket type'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_login',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='User login'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='User name'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seats',
            field=models.ManyToManyField(related_name='seats', to='movies.Seat'),
        ),
    ]
