# Generated by Django 4.0.4 on 2022-05-30 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Movie title')),
                ('small_description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Small description')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('poster', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Poster')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Premiere beginning')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Premiere ending')),
                ('movie_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Movie length')),
                ('category', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Movie category')),
                ('price', models.PositiveIntegerField(default=10, verbose_name='Movie price')),
                ('film_id', models.PositiveIntegerField(unique=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.PositiveIntegerField(blank=True, null=True, verbose_name='Seat')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='User name')),
                ('user_login', models.CharField(blank=True, max_length=250, null=True, verbose_name='User login')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date of movie')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='Movie date and time')),
                ('seat_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Seat count')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ticket type')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('seats', models.ManyToManyField(related_name='seats', to='movies.seat')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=250, null=True, verbose_name='User name')),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies.movie')),
            ],
        ),
    ]
