# Generated by Django 4.0.4 on 2022-06-01 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date of movie')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='Movie date and time')),
                ('seat', models.PositiveIntegerField(blank=True, null=True, verbose_name='Seat')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat_count',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user_name',
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Seat'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_first_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='User first name'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='User last name'),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
