# Generated by Django 4.0.4 on 2022-06-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_seats_remove_ticket_seat_count_remove_ticket_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Movie date and time'),
        ),
    ]
