# Generated by Django 4.0.4 on 2022-06-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_ticket_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seats',
            old_name='time',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='seats',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='time',
        ),
        migrations.AddField(
            model_name='ticket',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Movie date and time'),
        ),
    ]
