# Generated by Django 4.0.4 on 2022-06-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_time_seats_datetime_remove_seats_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
